/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AmountEnum = {
    NotEnough: 'NotEnough',
    Enough: 'Enough',
    MoreThanEnough: 'MoreThanEnough'
} as const;
export type AmountEnum = typeof AmountEnum[keyof typeof AmountEnum];


export function AmountEnumFromJSON(json: any): AmountEnum {
    return AmountEnumFromJSONTyped(json, false);
}

export function AmountEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AmountEnum {
    return json as AmountEnum;
}

export function AmountEnumToJSON(value?: AmountEnum | null): any {
    return value as any;
}

