/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssignmentDTO } from './AssignmentDTO';
import {
    AssignmentDTOFromJSON,
    AssignmentDTOFromJSONTyped,
    AssignmentDTOToJSON,
} from './AssignmentDTO';

/**
 * 
 * @export
 * @interface AssignmentDTOPagedResponse
 */
export interface AssignmentDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof AssignmentDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AssignmentDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof AssignmentDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<AssignmentDTO>}
     * @memberof AssignmentDTOPagedResponse
     */
    data?: Array<AssignmentDTO> | null;
}

/**
 * Check if a given object implements the AssignmentDTOPagedResponse interface.
 */
export function instanceOfAssignmentDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssignmentDTOPagedResponseFromJSON(json: any): AssignmentDTOPagedResponse {
    return AssignmentDTOPagedResponseFromJSONTyped(json, false);
}

export function AssignmentDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(AssignmentDTOFromJSON)),
    };
}

export function AssignmentDTOPagedResponseToJSON(value?: AssignmentDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(AssignmentDTOToJSON)),
    };
}

