/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssignmentDTOPagedResponse } from './AssignmentDTOPagedResponse';
import {
    AssignmentDTOPagedResponseFromJSON,
    AssignmentDTOPagedResponseFromJSONTyped,
    AssignmentDTOPagedResponseToJSON,
} from './AssignmentDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AssignmentDTOPagedResponseRequestResponse
 */
export interface AssignmentDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {AssignmentDTOPagedResponse}
     * @memberof AssignmentDTOPagedResponseRequestResponse
     */
    response?: AssignmentDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AssignmentDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AssignmentDTOPagedResponseRequestResponse interface.
 */
export function instanceOfAssignmentDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssignmentDTOPagedResponseRequestResponseFromJSON(json: any): AssignmentDTOPagedResponseRequestResponse {
    return AssignmentDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function AssignmentDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AssignmentDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AssignmentDTOPagedResponseRequestResponseToJSON(value?: AssignmentDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AssignmentDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

