/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssignmentDTO } from './AssignmentDTO';
import {
    AssignmentDTOFromJSON,
    AssignmentDTOFromJSONTyped,
    AssignmentDTOToJSON,
} from './AssignmentDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AssignmentDTORequestResponse
 */
export interface AssignmentDTORequestResponse {
    /**
     * 
     * @type {AssignmentDTO}
     * @memberof AssignmentDTORequestResponse
     */
    response?: AssignmentDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AssignmentDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AssignmentDTORequestResponse interface.
 */
export function instanceOfAssignmentDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssignmentDTORequestResponseFromJSON(json: any): AssignmentDTORequestResponse {
    return AssignmentDTORequestResponseFromJSONTyped(json, false);
}

export function AssignmentDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : AssignmentDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AssignmentDTORequestResponseToJSON(value?: AssignmentDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': AssignmentDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

