/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssignmentDTO } from './AssignmentDTO';
import {
    AssignmentDTOFromJSON,
    AssignmentDTOFromJSONTyped,
    AssignmentDTOToJSON,
} from './AssignmentDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AssignmentDTOServiceResponse
 */
export interface AssignmentDTOServiceResponse {
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AssignmentDTOServiceResponse
     */
    error?: ErrorMessage;
    /**
     * 
     * @type {boolean}
     * @memberof AssignmentDTOServiceResponse
     */
    readonly isOk?: boolean;
    /**
     * 
     * @type {AssignmentDTO}
     * @memberof AssignmentDTOServiceResponse
     */
    result?: AssignmentDTO;
}

/**
 * Check if a given object implements the AssignmentDTOServiceResponse interface.
 */
export function instanceOfAssignmentDTOServiceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssignmentDTOServiceResponseFromJSON(json: any): AssignmentDTOServiceResponse {
    return AssignmentDTOServiceResponseFromJSONTyped(json, false);
}

export function AssignmentDTOServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentDTOServiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorMessageFromJSON(json['error']),
        'isOk': !exists(json, 'isOk') ? undefined : json['isOk'],
        'result': !exists(json, 'result') ? undefined : AssignmentDTOFromJSON(json['result']),
    };
}

export function AssignmentDTOServiceResponseToJSON(value?: AssignmentDTOServiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorMessageToJSON(value.error),
        'result': AssignmentDTOToJSON(value.result),
    };
}

