/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssignmentDTO } from './AssignmentDTO';
import {
    AssignmentDTOFromJSON,
    AssignmentDTOFromJSONTyped,
    AssignmentDTOToJSON,
} from './AssignmentDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface AssignmentDTOListRequestResponse
 */
export interface AssignmentDTOListRequestResponse {
    /**
     * 
     * @type {Array<AssignmentDTO>}
     * @memberof AssignmentDTOListRequestResponse
     */
    readonly response?: Array<AssignmentDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof AssignmentDTOListRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the AssignmentDTOListRequestResponse interface.
 */
export function instanceOfAssignmentDTOListRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssignmentDTOListRequestResponseFromJSON(json: any): AssignmentDTOListRequestResponse {
    return AssignmentDTOListRequestResponseFromJSONTyped(json, false);
}

export function AssignmentDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignmentDTOListRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(AssignmentDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function AssignmentDTOListRequestResponseToJSON(value?: AssignmentDTOListRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

