/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AmountEnum } from './AmountEnum';
import {
    AmountEnumFromJSON,
    AmountEnumFromJSONTyped,
    AmountEnumToJSON,
} from './AmountEnum';

/**
 * 
 * @export
 * @interface FeedbackAddDTO
 */
export interface FeedbackAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    title?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackAddDTO
     */
    rating?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    comment?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackAddDTO
     */
    attendance?: number;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackAddDTO
     */
    understanding?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FeedbackAddDTO
     */
    engagement?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FeedbackAddDTO
     */
    assignmentCompletion?: number;
    /**
     * 
     * @type {AmountEnum}
     * @memberof FeedbackAddDTO
     */
    resources?: AmountEnum;
    /**
     * 
     * @type {AmountEnum}
     * @memberof FeedbackAddDTO
     */
    communication?: AmountEnum;
    /**
     * 
     * @type {string}
     * @memberof FeedbackAddDTO
     */
    subjectId?: string;
}

/**
 * Check if a given object implements the FeedbackAddDTO interface.
 */
export function instanceOfFeedbackAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackAddDTOFromJSON(json: any): FeedbackAddDTO {
    return FeedbackAddDTOFromJSONTyped(json, false);
}

export function FeedbackAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'attendance': !exists(json, 'attendance') ? undefined : json['attendance'],
        'understanding': !exists(json, 'understanding') ? undefined : json['understanding'],
        'engagement': !exists(json, 'engagement') ? undefined : json['engagement'],
        'assignmentCompletion': !exists(json, 'assignmentCompletion') ? undefined : json['assignmentCompletion'],
        'resources': !exists(json, 'resources') ? undefined : AmountEnumFromJSON(json['resources']),
        'communication': !exists(json, 'communication') ? undefined : AmountEnumFromJSON(json['communication']),
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
    };
}

export function FeedbackAddDTOToJSON(value?: FeedbackAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'rating': value.rating,
        'comment': value.comment,
        'attendance': value.attendance,
        'understanding': value.understanding,
        'engagement': value.engagement,
        'assignmentCompletion': value.assignmentCompletion,
        'resources': AmountEnumToJSON(value.resources),
        'communication': AmountEnumToJSON(value.communication),
        'subjectId': value.subjectId,
    };
}

