/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface Int32ServiceResponse
 */
export interface Int32ServiceResponse {
    /**
     * 
     * @type {ErrorMessage}
     * @memberof Int32ServiceResponse
     */
    error?: ErrorMessage;
    /**
     * 
     * @type {boolean}
     * @memberof Int32ServiceResponse
     */
    readonly isOk?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Int32ServiceResponse
     */
    result?: number;
}

/**
 * Check if a given object implements the Int32ServiceResponse interface.
 */
export function instanceOfInt32ServiceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Int32ServiceResponseFromJSON(json: any): Int32ServiceResponse {
    return Int32ServiceResponseFromJSONTyped(json, false);
}

export function Int32ServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Int32ServiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorMessageFromJSON(json['error']),
        'isOk': !exists(json, 'isOk') ? undefined : json['isOk'],
        'result': !exists(json, 'result') ? undefined : json['result'],
    };
}

export function Int32ServiceResponseToJSON(value?: Int32ServiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorMessageToJSON(value.error),
        'result': value.result,
    };
}

