/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { Professor } from './Professor';
import {
    ProfessorFromJSON,
    ProfessorFromJSONTyped,
    ProfessorToJSON,
} from './Professor';

/**
 * 
 * @export
 * @interface ProfessorServiceResponse
 */
export interface ProfessorServiceResponse {
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProfessorServiceResponse
     */
    error?: ErrorMessage;
    /**
     * 
     * @type {boolean}
     * @memberof ProfessorServiceResponse
     */
    readonly isOk?: boolean;
    /**
     * 
     * @type {Professor}
     * @memberof ProfessorServiceResponse
     */
    result?: Professor;
}

/**
 * Check if a given object implements the ProfessorServiceResponse interface.
 */
export function instanceOfProfessorServiceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfessorServiceResponseFromJSON(json: any): ProfessorServiceResponse {
    return ProfessorServiceResponseFromJSONTyped(json, false);
}

export function ProfessorServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfessorServiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': !exists(json, 'error') ? undefined : ErrorMessageFromJSON(json['error']),
        'isOk': !exists(json, 'isOk') ? undefined : json['isOk'],
        'result': !exists(json, 'result') ? undefined : ProfessorFromJSON(json['result']),
    };
}

export function ProfessorServiceResponseToJSON(value?: ProfessorServiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': ErrorMessageToJSON(value.error),
        'result': ProfessorToJSON(value.result),
    };
}

