/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface ProfessorDTO
 */
export interface ProfessorDTO {
    /**
     * 
     * @type {string}
     * @memberof ProfessorDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfessorDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfessorDTO
     */
    email?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof ProfessorDTO
     */
    role?: UserRoleEnum;
}

/**
 * Check if a given object implements the ProfessorDTO interface.
 */
export function instanceOfProfessorDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfessorDTOFromJSON(json: any): ProfessorDTO {
    return ProfessorDTOFromJSONTyped(json, false);
}

export function ProfessorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfessorDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
    };
}

export function ProfessorDTOToJSON(value?: ProfessorDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'role': UserRoleEnumToJSON(value.role),
    };
}

