/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ProfessorDTO } from './ProfessorDTO';
import {
    ProfessorDTOFromJSON,
    ProfessorDTOFromJSONTyped,
    ProfessorDTOToJSON,
} from './ProfessorDTO';

/**
 * 
 * @export
 * @interface ProfessorDTOListRequestResponse
 */
export interface ProfessorDTOListRequestResponse {
    /**
     * 
     * @type {Array<ProfessorDTO>}
     * @memberof ProfessorDTOListRequestResponse
     */
    readonly response?: Array<ProfessorDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ProfessorDTOListRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ProfessorDTOListRequestResponse interface.
 */
export function instanceOfProfessorDTOListRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProfessorDTOListRequestResponseFromJSON(json: any): ProfessorDTOListRequestResponse {
    return ProfessorDTOListRequestResponseFromJSONTyped(json, false);
}

export function ProfessorDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfessorDTOListRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(ProfessorDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ProfessorDTOListRequestResponseToJSON(value?: ProfessorDTOListRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

