/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { StudentDTO } from './StudentDTO';
import {
    StudentDTOFromJSON,
    StudentDTOFromJSONTyped,
    StudentDTOToJSON,
} from './StudentDTO';

/**
 * 
 * @export
 * @interface StudentDTORequestResponse
 */
export interface StudentDTORequestResponse {
    /**
     * 
     * @type {StudentDTO}
     * @memberof StudentDTORequestResponse
     */
    response?: StudentDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StudentDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the StudentDTORequestResponse interface.
 */
export function instanceOfStudentDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentDTORequestResponseFromJSON(json: any): StudentDTORequestResponse {
    return StudentDTORequestResponseFromJSONTyped(json, false);
}

export function StudentDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : StudentDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StudentDTORequestResponseToJSON(value?: StudentDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': StudentDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

