/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { StudentDTOPagedResponse } from './StudentDTOPagedResponse';
import {
    StudentDTOPagedResponseFromJSON,
    StudentDTOPagedResponseFromJSONTyped,
    StudentDTOPagedResponseToJSON,
} from './StudentDTOPagedResponse';

/**
 * 
 * @export
 * @interface StudentDTOPagedResponseRequestResponse
 */
export interface StudentDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {StudentDTOPagedResponse}
     * @memberof StudentDTOPagedResponseRequestResponse
     */
    response?: StudentDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StudentDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the StudentDTOPagedResponseRequestResponse interface.
 */
export function instanceOfStudentDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentDTOPagedResponseRequestResponseFromJSON(json: any): StudentDTOPagedResponseRequestResponse {
    return StudentDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function StudentDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : StudentDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StudentDTOPagedResponseRequestResponseToJSON(value?: StudentDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': StudentDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

