/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StudentDTO } from './StudentDTO';
import {
    StudentDTOFromJSON,
    StudentDTOFromJSONTyped,
    StudentDTOToJSON,
} from './StudentDTO';

/**
 * 
 * @export
 * @interface StudentDTOPagedResponse
 */
export interface StudentDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof StudentDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof StudentDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof StudentDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<StudentDTO>}
     * @memberof StudentDTOPagedResponse
     */
    data?: Array<StudentDTO> | null;
}

/**
 * Check if a given object implements the StudentDTOPagedResponse interface.
 */
export function instanceOfStudentDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudentDTOPagedResponseFromJSON(json: any): StudentDTOPagedResponse {
    return StudentDTOPagedResponseFromJSONTyped(json, false);
}

export function StudentDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(StudentDTOFromJSON)),
    };
}

export function StudentDTOPagedResponseToJSON(value?: StudentDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(StudentDTOToJSON)),
    };
}

