/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubjectUpdateDTO
 */
export interface SubjectUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubjectUpdateDTO
     */
    professorId?: string;
}

/**
 * Check if a given object implements the SubjectUpdateDTO interface.
 */
export function instanceOfSubjectUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubjectUpdateDTOFromJSON(json: any): SubjectUpdateDTO {
    return SubjectUpdateDTOFromJSONTyped(json, false);
}

export function SubjectUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'professorId': !exists(json, 'professorId') ? undefined : json['professorId'],
    };
}

export function SubjectUpdateDTOToJSON(value?: SubjectUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'professorId': value.professorId,
    };
}

